name: Deploy GitHub Pages
run-name: Deploy GitHub Pages
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:21-alpine
      env:
        NODE_ENV: "development"
    steps:
      #busybox tar does not have `--hard-dereference`, which is used by `actions/upload-pages-artifact@v3`
      - name: Install Dependencies
        run: (apk add --no-cache tar && tar --version)
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Packages
        working-directory: astro
        run: (npm ci)
      - name: Lint Project
        working-directory: astro
        run: (npm run lint)
      - name: Build Project
        working-directory: astro
        run: (npm run build -- --site https://code4community-lexington.github.io --base organization.website)
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "astro/dist/"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
