name: Lint
run-name: Lint
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
jobs:
  Lint:
    runs-on: ubuntu-latest
    container:
      image: node:21-alpine
      env:
        NODE_ENV: "development"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Packages
        working-directory: astro
        run: (npm ci)
      - name: Lint Fix
        working-directory: astro
        run: (npm run fix)
      - name: Lint Project
        working-directory: astro
        run: (npm run lint)
